### ISSUE TITLE
Instructions to training the model

### ISSUE THREAD

**Issue by ghost** [Bui1dMySea/MemLong#1]
Hi,

Thanks so much for your excellent work! When would you be able to share the instructions about data processing and training the model?

Thanks!

**Comment by Bui1dMySea** [comment]
Hi,
we will upload all the code and illustrations before the beginning of October! 
Please be patient.

**Comment by GhadirAlsewi** [comment]
Hello,

I really appreciate the great work you've done! Could you let me know when you'll be able to provide the guidelines for processing the data and training the model?

Thanks!

**Comment by Bui1dMySea** [comment]
We have provided most of the code and scripts now!
