### ISSUE TITLE
Missed Training Essential values for the code Arguments

### ISSUE THREAD

**Issue by RedaHani** [Bui1dMySea/MemLong#2]
Thank you for this great work. 
I started to run the code but the essential arguments are missing in the Readme file. Also, in the article as well since not all of the required arguments values are mentioned clearly. 
I hope you share the illustrations and the arguments quickly since it has been 2 months since you created this repository but no one can use it unfortunately due the missing arguments.

**Comment by Bui1dMySea** [comment]
We have provided most of the code and scripts now
